
CREATE TABLE IF NOT EXISTS ratings(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
store_id INT NOT NULL,
rating TINYINT NOT NULL,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY uq_user_store (user_id, store_id),
CONSTRAINT chk_rating CHECK (rating BETWEEN 1 AND 5),
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE)
