
CREATE TABLE IF NOT EXISTS stores(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(60) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
address VARCHAR(400) NOT NULL,
owner_id INT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL);
